### ISSUE TITLE
Add N26 as an alternative of EU Bank Account

### ISSUE THREAD

**Issue by fernandosouza** [brazil-tech-expats/wiki#1]

**Comment by djalmaaraujo** [comment]
@fernandosouza Can you provide an official link to the bank website, app, etc? Maybe the fees page. Why is this bank good? Is it easy to create an account?

**Comment by fernandosouza** [comment]
Sure. I'm going to send a PR.

**Comment by murielsilveira** [comment]
@fernandosouza já colocamos o GitBook pra rodar, se quiser aproveitar pra mandar as informações :)

**Comment by djalmaaraujo** [comment]
N26 agora disponivel em PT 🇵🇹  :)

**Comment by djalmaaraujo** [comment]
@fernandosouza Closing until we have a pr
