### ISSUE TITLE
Discussion: Renomear branch principal de master pra main

### ISSUE THREAD

**Issue by gmmcal** [brazil-tech-expats/wiki#14]
Seria bom renomear o branch principal de `master` para `main` pra tornar o repositório um pouco mais inclusivo. Aparentemente, a origem do movimento foi [iniciada aqui](https://lore.kernel.org/git/CAOAHyQwyXC1Z3v7BZAC+Bq6JBaM7FvBenA-1fcqeDV==apdWDg@mail.gmail.com/)

O github permite a troca da configuração de maneira trivial nos ajustes do repositório.

Eu gostaria de abrir a discussão sobre renomear ou não o branch principal antes de fazer em definitivo.

**Comment by felipecsl** [comment]
Por mim é indiferente, não me oponho 👍

**Comment by lucasew** [comment]
Tanto faz.

Em todos os projetos eu deixo padrão e nem penso sobre isso.

Como eu gero basicamente todos os repos locais usando o git cli mesmo ele sempre inicializa como master, quando crio pelo gh pra editar pelo gh e tal ele cria como main.

Pessoalmente para mim não faz diferença a não ser a memória muscular que me trai as vezes hehehe.

Não critico o movimento mas também não tomo nenhuma atitude de migração do que eu já tenho.

**Comment by janosimas** [comment]
Um ponto a favor é que `main` vai ser o default do github a partir de agora.

**Comment by arthurgeek** [comment]
@gmmcal valeu pela sugestão. feito.
