### ISSUE TITLE
Legendas em pt-br no Netflix fora do Brasil

### ISSUE THREAD

**Issue by diegoaad** [brazil-tech-expats/wiki#2]
Além da dica do VPN pra acessar o catalogo do brasil no Netflix. Esses dias alguém comentou sobre legendas, se o usuário quiser ter legendas em pt-br basta apenas configurar o idioma do perfil do Netflix pra Português (Brasil).

**Comment by murielsilveira** [comment]
Não sei qual era o link @diegoaad, mas esse será que ajuda: https://help.netflix.com/en/node/13245 ?

**Comment by habutre** [comment]
Eu já entrei em contato duas vezes com o suporte Netflix, mas a super dica é selecionar o idioma no catálogo. Mas não se anime porque os títulos que possuem legendas ou audio em PT (alguns pt_PT) são bem meh!

A dica da VPN deve funcionar melhor não tentei

**Comment by djalmaaraujo** [comment]
A VPN não funciona. Netflix é esperto.

**Comment by diegoaad** [comment]
Acho que o principal mesmo é sobre a linguagem do Netflix pra habilitar novas legendas. Sobre o catalogo, nem tentei acessar o catalogo de outros paises com VPN, mas já imaginava isso.

**Comment by djalmaaraujo** [comment]
Alguem confirma sobre o idioma da legenda? Para mim sempre fica portugues de portugal? Quero fechar a issue se ng confirmar :)

**Comment by diegoaad** [comment]
Eu moro nos EUA, antigamente qdo a linguagem do Netflix tava com Inglês, eu só conseguia legendas em Inglês ou Espanhol. Após modificar meu perfil no Netflix pra Português, as legendas em Português (BR) ficaram disponiveis. Agora não sei se estando em Portugal o Netflix automaticamente muda pra pt-pt

**Comment by habutre** [comment]
Meu perfil é `pt_BR` mas as legendas seguem o país de onde você acessa e não o definido no seu perfil. Aqui pra mim é sempre Alemão e Inglês por default, e se tiver filmes disponíveis em `pt_(BR|PT)` aí sim você terá esses áudio ou legenda disponíveis.

**Comment by djalmaaraujo** [comment]
Em PT, consigo ver português e português - europeu.

![image 2018-10-05 at 4 52 23 pm](https://user-images.githubusercontent.com/3402/46545759-26333900-c8bf-11e8-97e9-06f184049d83.png)

Fechando a issue, caso alguém queira abrir uma PR informando, fica a vontade.
