### ISSUE TITLE
Static website

### ISSUE THREAD

**Issue by murielsilveira** [brazil-tech-expats/wiki#3]
O que acha de usar o [gitbook](https://github.com/GitbookIO/gitbook) para a wiki?
Acho bem interessante as opções de leitura e os links para edição.
eg.: https://redux-observable.js.org

Ou tem alguma outra ideia?

**Comment by djalmaaraujo** [comment]
Acho otimo. Quer fazer o primeiro setup?

**Comment by murielsilveira** [comment]
Topo sim, farei final de semana :)

**Comment by murielsilveira** [comment]
Should we go with the root level setup or something like `/docs`?

**Comment by murielsilveira** [comment]
vou precisar de acesso ao repo pra configurar também :)

**Comment by djalmaaraujo** [comment]
Ta com acesso.

**Comment by murielsilveira** [comment]
Com a permissão atual ainda não consigo adicionar no GitBook: https://help.gitbook.com/github/can-i-host-on-github.html

Mas migrei o conteúdo da wiki atual e adicionei algumas instruções no readme :)

**Comment by djalmaaraujo** [comment]
@murielsilveira Pronto, admin added. Muito bom, vou revisar a pr agora.

**Comment by djalmaaraujo** [comment]
Fixed in #5
