### ISSUE TITLE
Get a domain

### ISSUE THREAD

**Issue by murielsilveira** [brazil-tech-expats/wiki#4]

**Comment by murielsilveira** [comment]
tem muitas [opções](https://domains.google.com/registrar?s=brazil-tech-expats#st=a&chp=st), selecionei alguns aleatórios, o que acham?

- `brazil-tech-expats.com`
- `brazil-tech-expats.io`
- `brazil-tech-expats.org`
- `brazil-tech-expats.world`
- `brazil-tech-expats.guide`
- `brazil-tech-expats.guru`
- `brazil-tech-expats.foundation`
- `brazil-tech-expats.network`
- `brazil-tech-expats.rocks`
- `brazil-tech-expats.tips`
- `brazil-tech-expats.zone`

**Comment by djalmaaraujo** [comment]
Vou perguntar aos admins e digo aqui.

**Comment by djalmaaraujo** [comment]
Sem manifestos.
