### ISSUE TITLE
Relocation tips about Netherlands

### ISSUE THREAD

**Issue by paulovitorbal** [brazil-tech-expats/wiki#7]
I am moving to the Netherlands and I want to collaborate with some tips.

How is the best way to do this?

**Comment by djalmaaraujo** [comment]
Open a PR :) @paulovitorbal 

Everything is it's early stages, just open a PR and we can organize together the content

**Comment by paulovitorbal** [comment]
#8 I opened a PR. Please, check it out.

**Comment by paulovitorbal** [comment]
I opened another PR. Now with some information about the migration process. #9
